---
title: "Position Plots"
author: "Jiahao Huo 404451256"
date: "June 2, 2017"
output: pdf_document
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(ggforce)
Final_nbadat <- read.csv("~/Desktop/Final Report/Final_nbadat.csv")
salary<- read.csv("~/Desktop/Final Report/salary.csv")
data1 <- read.csv("~/Desktop/Final Report/new_jiahao.txt")
features <- read.csv("~/Desktop/Final Report/features_sum.csv")
Final_nbadat<-Final_nbadat[,c(-1,-3)]
nbadat_valid<-Final_nbadat[which(Final_nbadat$FGA>=300),]
final_data <- read.csv("~/Desktop/Final Report/final_data")
standardize<-function(x){(x-min(x))/(max(x)-min(x))}
final_data$REBs<-final_data$DREBs+final_data$OREBs
final_data$FBR<-final_data$FGMs+final_data$BLKs+final_data$REBs
final_data$FAD<-final_data$FGMs+final_data$ASTs+final_data$DREBs
final_data$FADT<-final_data$FGMs+final_data$ASTs+final_data$DREBs+final_data$TOVs
final_data$FD<-final_data$FGMs+final_data$DREBs
```


#Center
```{r}
final_C<-final_data[which(final_data$Positions=="C"),]
final_C$avg<-(final_C$FGP_rank*final_C$FGMs+final_C$BLK_rank*final_C$BLKs+final_C$REB_rank*final_C$REBs)/final_C$FBR
final_C$salary<-standardize(final_C$salary)
final_C$avg<-standardize(final_C$avg)
final_C$dis<-(final_C$avg)^2+(final_C$salary)^2
final_C<-final_C[order(final_C$dis),]
final_C$dis_rank<-1:nrow(final_C)
final_C_table<-final_C %>% select(player, FGP, BLK, REB)
head(final_C_table,n=3)

textdfCenter <- data.frame(final_C[final_C$player %in% final_C$player[c(1:3)], ])
center <- ggplot(data = final_C, aes(x = avg, y = salary, colour=dis)) +
  geom_point(size = 4) +
  geom_point(shape = 1,size = 4,colour = "black") + 
  #geom_text(data = textdf, aes(x = avg * 1.05, y = salary*0.9, label = "" )) +
  annotate("text", x = textdfCenter$avg[1], y = textdfCenter$salary[1], label = 1) +
  annotate("text", x = textdfCenter$avg[2], y = textdfCenter$salary[2], label = 2) +
  annotate("text", x = textdfCenter$avg[3], y = textdfCenter$salary[3], label = 3) +
  scale_color_gradient2(name = "Distance to\n the Origin", low = "yellow", high = "black",mid="red",midpoint = 0.5)+
  theme(text=element_text(family="CM Roman")) +
  theme_classic(base_size = 9) + 
  labs(title="Position Plot: Center", x = "Weighted Rank", y = "Salary") +
  theme(panel.grid.major = element_line(size = .5, color = "grey"),
  legend.position = c(.84,.73),
  axis.line = element_line(size=.85, color = "black"))
```

#Power Forward
```{r}
final_PF<-final_data[which(final_data$Positions=="PF"),]
final_PF$avg<-(final_PF$FGP_rank*final_PF$FGMs+final_PF$BLK_rank*final_PF$BLKs+final_PF$REB_rank*final_PF$REBs)/final_PF$FBR
final_PF$salary<-standardize(final_PF$salary)
final_PF$avg<-standardize(final_PF$avg)
final_PF$dis<-(final_PF$avg)^2+(final_PF$salary)^2
final_PF<-final_PF[order(final_PF$dis),]
final_PF$dis_rank<-1:nrow(final_PF)
final_PF_table<-final_PF %>% select(player, FGP, BLK, REB)
head(final_PF_table,n=3)

textdfPF <- final_PF[final_PF$player %in% final_PF$player[c(1:3)], ]
powerForward <- ggplot(data = final_PF, aes(x = avg, y = salary,colour=dis)) +
  geom_point(size = 4) +
  geom_point(shape = 1, size = 4, colour = "black") + 
  annotate("text", x = textdfPF$avg[1], y = textdfPF$salary[1], label = 1) +
  annotate("text", x = textdfPF$avg[2], y = textdfPF$salary[2], label = 2) +
  annotate("text", x = textdfPF$avg[3], y = textdfPF$salary[3], label = 3) +
  scale_color_gradient2(name = "Distance to\n the Origin", low = "yellow", high = "black",mid="red",midpoint = 0.5)+
  theme(text=element_text(family="CM Roman"))+
  labs(title="Position Plot: Power Forward", x = "Weighted Rank", y = "Salary") + 
  theme_classic(base_size = 9) +
  theme(panel.grid.major = element_line(size = .5, color = "grey"),
  legend.position = c(.84,.73),
  axis.line = element_line(size=.85, color = "black")) 
```

#Shooting Guard
```{r}
final_SG<-final_data[which(final_data$Positions=="SG"),]
final_SG$avg<-(final_SG$FGP_rank*final_SG$FGMs+final_SG$AST_rank*final_SG$ASTs+final_SG$DREB_rank*final_SG$DREBs)/final_SG$FAD
final_SG$salary<-standardize(final_SG$salary)
final_SG$avg<-standardize(final_SG$avg)
final_SG$dis<-(final_SG$avg)^2+(final_SG$salary)^2
final_SG<-final_SG[order(final_SG$dis),]
final_SG$dis_rank<-1:nrow(final_SG)
final_SG_table<-final_SG %>% select(player, FGP, AST, DREB)
head(final_SG_table,n=3)


textdfSG <- final_SG[final_SG$player %in% final_SG$player[c(1:3)], ]
shootingGuard <- ggplot(data = final_SG, aes(x = avg, y = salary,colour=dis)) +
  geom_point(size = 4) +
  geom_point(shape = 1, size = 4, colour = "black") + 
  annotate("text", x = textdfSG$avg[1], y = textdfSG$salary[1], label = 1) +
  annotate("text", x = textdfSG$avg[2], y = textdfSG$salary[2], label = 2) +
  annotate("text", x = textdfSG$avg[3], y = textdfSG$salary[3], label = 3) +
  scale_color_gradient2(name = "Distance to\n the Origin", low = "yellow", high = "black",mid="red",midpoint = 0.5)+
  theme(text=element_text(family="CM Roman"))+
  labs(title="Position Plot: Shooting Guard", x = "Weighted Rank", y = "Salary") + 
  theme_classic(base_size = 9) +
  theme(panel.grid.major = element_line(size = .5, color = "grey"),
  legend.position = c(.84,.73),
  axis.line = element_line(size=.85, color = "black"))
```

#Point Guard
```{r}
final_PG<-final_data[which(final_data$Positions=="PG"),]
final_PG$avg<-(final_PG$FGP_rank*final_PG$FGMs+final_PG$AST_rank*final_PG$ASTs+final_PG$DREB_rank*final_PG$DREBs+final_PG$TOV_rank*final_PG$TOVs)/final_PG$FADT
final_PG$salary<-standardize(final_PG$salary)
final_PG$avg<-standardize(final_PG$avg)
final_PG$dis<-(final_PG$avg)^2+(final_PG$salary)^2
final_PG<-final_PG[order(final_PG$dis),]
final_PG$dis_rank<-1:nrow(final_PG)
final_PG_table<-final_PG %>% select(player, FGP, AST, DREB,TOV)
head(final_PG_table,n=3)

textdfPG <- final_PG[final_PG$player %in% final_PG$player[c(1:3)],]
pointGuard <- ggplot(data = final_PG, aes(x = avg, y = salary,colour=dis)) +
  geom_point(size = 4) +
  geom_point(shape = 1, size = 4, colour = "black") + 
  annotate("text", x = textdfPG$avg[1], y = textdfPG$salary[1], label = 1) +
  annotate("text", x = textdfPG$avg[2], y = textdfPG$salary[2], label = 2) +
  annotate("text", x = textdfPG$avg[3], y = textdfPG$salary[3], label = 3) +
  scale_color_gradient2(name = "Distance to\n the Origin", low = "yellow", high = "black",mid="red",midpoint = 0.5)+
  theme(text=element_text(family="CM Roman"))+
  labs(title="Position Plot: Point Guard", x = "Weighted Rank", y = "Salary") + 
  theme_classic(base_size = 9) +
  theme(panel.grid.major = element_line(size = .5, color = "grey"),
  legend.position = c(.84,.73),
  axis.line = element_line(size=.85, color = "black"))
```

#Small Forward
```{r}
final_SF<-final_data[which(final_data$Positions=="SF"),]
final_SF$avg<-(final_SF$FGP_rank*final_SF$FGMs+final_SF$DREB_rank*final_SF$DREBs)/final_SF$FD
final_SF$salary<-standardize(final_SF$salary)
final_SF$avg<-standardize(final_SF$avg)
final_SF$dis<-(final_SF$avg)^2+(final_SF$salary)^2
final_SF<-final_SF[order(final_SF$dis),]
final_SF$dis_rank<-1:nrow(final_SF)
final_SF_table<-final_SF %>% select(player, FGP, DREB)
head(final_SF_table,n=3)

textdfSF <- final_SF[final_SF$player %in% final_SF$player[c(1:3)], ]
smallForward <- ggplot(data = final_SF, aes(x = avg, y = salary,colour=dis)) +
  geom_point(size = 4) +
  geom_point(shape = 1, size = 4, colour = "black") + 
  annotate("text", x = textdfSF$avg[1], y = textdfSF$salary[1], label = 1) +
  annotate("text", x = textdfSF$avg[2], y = textdfSF$salary[2], label = 2) +
  annotate("text", x = textdfSF$avg[3], y = textdfSF$salary[3], label = 3) +
  scale_color_gradient2(name = "Distance to\n the Origin", low = "yellow", high = "black",mid="red",midpoint = 0.5)+
  theme(text=element_text(family="CM Roman"))+
  labs(title="Position Plot: Small Forward", x = "Weighted Rank", y = "Salary")+
  theme_classic(base_size = 9) +
  theme(panel.grid.major = element_line(size = .5, color = "grey"),
  legend.position = c(.84,.73),
  axis.line = element_line(size=.85, color = "black"))
```

